# Generated by Django 4.1.7 on 2023-03-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seller_zakaz_terminal_seller_zakaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
