# Generated by Django 4.1.7 on 2023-03-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_pizza_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
