# Generated by Django 4.1.7 on 2023-03-06 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pizza_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='zakaz',
            new_name='zakazSeller',
        ),
        migrations.AddField(
            model_name='zakaz',
            name='sellerZakaz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.seller'),
        ),
    ]
